import React, { useState } from 'react';
import type { PaperSummary } from '../types';
import SectionCard from './SectionCard';
import { 
  TldrIcon, NewIcon, HowItWorksIcon, EvidenceIcon, ProductIcon, AppsIcon, 
  RisksIcon, GlossaryIcon, QuestionsIcon, QuotesIcon, CopyIcon, EmailIcon, InfoIcon
} from './icons';
import Feedback from './Feedback';

// A simple animation component
const FadeIn: React.FC<{children: React.ReactNode}> = ({ children }) => {
    const [isMounted, setIsMounted] = React.useState(false);
    React.useEffect(() => {
        setIsMounted(true);
    }, []);
    return (
        <div className={`transition-opacity duration-700 ease-in ${isMounted ? 'opacity-100' : 'opacity-0'}`}>
            {children}
        </div>
    );
}

interface ResultsDisplayProps {
  summary: PaperSummary;
}

const formatSummaryForEmail = (summary: PaperSummary): string => {
  let text = `Your TLDR Paper Summary:\n\n`;
  text += `Executive TL;DR\n-----------------\n${summary.executiveTldr}\n\n`;
  text += `What’s Actually New\n-------------------\n- The Leap: ${summary.whatIsNew.leap}\n- Compared to the Norm: ${summary.whatIsNew.comparison}\n\n`;
  text += `How It Works (Plain English)\n----------------------------\n- Metaphor: "${summary.howItWorks.metaphor}"\n- The Logic: ${summary.howItWorks.logic}\n\n`;
  text += `Evidence & Limits\n-----------------\n${summary.evidenceAndLimits}\n\n`;
  text += `Product Implications\n--------------------\n- User Experience: ${summary.productImplications.userExperience}\n- Metrics: ${summary.productImplications.metrics}\n- Infrastructure: ${summary.productImplications.infra}\n- Team Org: ${summary.productImplications.teamOrg}\n\n`;
  text += `Real-World Applications & Analogies\n-----------------------------------\n${summary.realWorldApplications.map(app => `- ${app}`).join('\n')}\n\n`;
  text += `Risks & Guardrails\n------------------\n${summary.risksAndGuardrails}\n\n`;
  text += `Glossary\n--------\n${summary.glossary.map(item => `- ${item.term}: ${item.definition}`).join('\n')}\n\n`;
  text += `Questions to Ask\n----------------\n${summary.questionsToAsk.map((q) => `- ${q}`).join('\n')}\n\n`;
  text += `Citations & Pull-quotes\n-------------------------\n${summary.citationsAndPullQuotes.map(c => `"${c.quote}"\n- ${c.citation}`).join('\n\n')}\n\n`;
  text += `Generated by TLDR Paper - PM Edition`;
  return text;
};

const formatSummaryForMarkdown = (summary: PaperSummary): string => {
    let md = ``;
    md += `# TLDR Paper Summary\n\n`;
    md += `## Executive TL;DR\n${summary.executiveTldr}\n\n`;
    md += `## What’s Actually New\n`;
    md += `**The Leap:** ${summary.whatIsNew.leap}\n`;
    md += `**Compared to the Norm:** ${summary.whatIsNew.comparison}\n\n`;
    md += `## How It Works (Plain English)\n`;
    md += `**Metaphor:** _"${summary.howItWorks.metaphor}"_\n`;
    md += `**The Logic:** ${summary.howItWorks.logic}\n\n`;
    md += `## Evidence & Limits\n${summary.evidenceAndLimits}\n\n`;
    md += `## Product Implications\n`;
    md += `*   **User Experience:** ${summary.productImplications.userExperience}\n`;
    md += `*   **Metrics:** ${summary.productImplications.metrics}\n`;
    md += `*   **Infrastructure:** ${summary.productImplications.infra}\n`;
    md += `*   **Team Org:** ${summary.productImplications.teamOrg}\n\n`;
    md += `## Real-World Applications & Analogies\n${summary.realWorldApplications.map(app => `* ${app}`).join('\n')}\n\n`;
    md += `## Risks & Guardrails\n${summary.risksAndGuardrails}\n\n`;
    md += `## Glossary\n${summary.glossary.map(item => `*   **${item.term}:** ${item.definition}`).join('\n')}\n\n`;
    md += `## Questions to Ask\n${summary.questionsToAsk.map((q) => `* ${q}`).join('\n')}\n\n`;
    md += `## Citations & Pull-quotes\n${summary.citationsAndPullQuotes.map(c => `> "${c.quote}"\n> — ${c.citation}`).join('\n\n')}\n\n`;
    md += `---\n_Generated by TLDR Paper - PM Edition_`;
    return md;
};


const linkify = (text: string): React.ReactNode[] => {
    // Regex for standard URLs and arXiv IDs. This avoids including common trailing punctuation in the URL.
    const combinedRegex = /(https?:\/\/[^\s.,!?)\]}]+|www\.[^\s.,!?)\]}]+|arXiv:\d{4}\.\d{4,5}(v\d+)?)/g;

    if (!text) return [text];

    const parts = text.split(combinedRegex);

    return parts.map((part, index) => {
        if (!part) return null; // Handle potential empty strings from split

        // Check if the current part is one of the delimiters we split by
        if (part.match(combinedRegex)) {
            let href = '';
            if (part.startsWith('arXiv:')) {
                const arxivId = part.split(':')[1];
                href = `https://arxiv.org/abs/${arxivId}`;
            } else {
                href = part.startsWith('www.') ? `https://${part}` : part;
            }
            return (
                <a href={href} key={index} target="_blank" rel="noopener noreferrer" className="text-slate-600 hover:text-slate-900 underline decoration-slate-400 hover:decoration-slate-900 transition-colors">
                    {part}
                </a>
            );
        }
        return part; // This part is just plain text
    }).filter(part => part !== null); // Remove any null entries
};

const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ summary }) => {
  const [showEmailInput, setShowEmailInput] = useState(false);
  const [email, setEmail] = useState('');
  const [copyButtonText, setCopyButtonText] = useState('Copy Markdown');

  const handleCopy = () => {
    const markdown = formatSummaryForMarkdown(summary);
    navigator.clipboard.writeText(markdown).then(() => {
        setCopyButtonText('Copied!');
        setTimeout(() => setCopyButtonText('Copy Markdown'), 2000);
    }).catch(err => {
        console.error('Failed to copy text: ', err);
        setCopyButtonText('Copy Failed');
        setTimeout(() => setCopyButtonText('Copy Markdown'), 2000);
    });
  };

  const handleEmailSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email) return;

    const subject = "Your TLDR Paper Summary";
    const body = formatSummaryForEmail(summary);
    const mailtoLink = `mailto:${email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailtoLink;
    setShowEmailInput(false);
    setEmail('');
  };

  return (
    <div className="max-h-[calc(100vh-4rem)] overflow-y-auto pr-4 -mr-4">
        <FadeIn>
          {/* Action Bar */}
          <div className="bg-slate-50 rounded-lg p-3 mb-6 flex flex-col gap-4 border border-slate-200">
             <div className="flex items-center justify-end gap-3">
                <button 
                  onClick={() => setShowEmailInput(!showEmailInput)} 
                  className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-slate-700 bg-white border border-slate-300 rounded-md hover:bg-slate-100 transition-colors focus:outline-none focus:ring-2 focus:ring-slate-500"
                  aria-expanded={showEmailInput}
                >
                    <EmailIcon />
                    <span>Email Summary</span>
                </button>
                <button 
                  onClick={handleCopy}
                  className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-slate-800 rounded-md hover:bg-slate-700 transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-800"
                >
                    <CopyIcon />
                    <span>{copyButtonText}</span>
                </button>
              </div>
              {showEmailInput && (
                <div className="border-t border-slate-200 pt-4">
                  <form onSubmit={handleEmailSubmit} className="flex flex-col sm:flex-row items-center gap-3">
                      <input
                          type="email"
                          value={email}
                          onChange={(e) => setEmail(e.target.value)}
                          placeholder="Enter your email address"
                          required
                          className="flex-grow w-full sm:w-auto p-2 bg-white border border-slate-300 rounded-md text-sm focus:ring-slate-800 focus:border-slate-800"
                          aria-label="Email address"
                      />
                      <div className="flex gap-2 flex-shrink-0">
                          <button type="submit" className="px-4 py-2 text-sm font-semibold text-white bg-slate-800 rounded-md hover:bg-slate-700">Send</button>
                          <button type="button" onClick={() => setShowEmailInput(false)} className="px-4 py-2 text-sm font-semibold text-slate-700 bg-white border border-slate-300 rounded-md hover:bg-slate-100">Cancel</button>
                      </div>
                  </form>
                  <p className="text-xs text-slate-500 mt-2 text-center sm:text-left">This will open your default email client to send the summary.</p>
                </div>
              )}
          </div>
          
          <div className="bg-slate-100 text-slate-600 text-sm p-3 rounded-md flex items-start gap-3 mb-6">
              <div className="flex-shrink-0 pt-0.5 text-slate-500">
                  <InfoIcon />
              </div>
              <p>
                  <strong>Pro-Tip:</strong> This summary is an editable document. Click into the text to make changes, then select and copy (Ctrl/Cmd+C) to paste rich text into your favorite editor.
              </p>
          </div>

          <div 
            contentEditable={true}
            suppressContentEditableWarning={true}
            className="bg-white rounded-lg border border-slate-200 p-6 md:p-8 focus:outline-none focus:ring-2 focus:ring-slate-800 prose prose-slate max-w-none"
            aria-label="Editable summary document"
          >
              <SectionCard title="Executive TL;DR" icon={<TldrIcon />}>
                <p>{summary.executiveTldr}</p>
              </SectionCard>
        
              <SectionCard title="What’s Actually New" icon={<NewIcon />}>
                <h3 className="font-semibold text-slate-900">The Leap</h3>
                <p className="mb-3">{summary.whatIsNew.leap}</p>
                <h3 className="font-semibold text-slate-900">Compared to the Norm</h3>
                <p>{summary.whatIsNew.comparison}</p>
              </SectionCard>
        
              <SectionCard title="How It Works (Plain English)" icon={<HowItWorksIcon />}>
                 <h3 className="font-semibold text-slate-900">Metaphor</h3>
                 <p className="mb-3 italic">"{summary.howItWorks.metaphor}"</p>
                 <h3 className="font-semibold text-slate-900">The Logic</h3>
                 <p>{summary.howItWorks.logic}</p>
              </SectionCard>
              
              <SectionCard title="Evidence & Limits" icon={<EvidenceIcon />}>
                <p>{summary.evidenceAndLimits}</p>
              </SectionCard>
        
              <SectionCard title="Product Implications" icon={<ProductIcon />}>
                <ul className="space-y-3">
                  <li><strong className="text-slate-900 font-semibold">User Experience:</strong> {summary.productImplications.userExperience}</li>
                  <li><strong className="text-slate-900 font-semibold">Metrics:</strong> {summary.productImplications.metrics}</li>
                  <li><strong className="text-slate-900 font-semibold">Infrastructure:</strong> {summary.productImplications.infra}</li>
                  <li><strong className="text-slate-900 font-semibold">Team Org:</strong> {summary.productImplications.teamOrg}</li>
                </ul>
              </SectionCard>
        
              <SectionCard title="Real-World Applications & Analogies" icon={<AppsIcon />}>
                <ul className="list-disc list-inside space-y-2">
                  {summary.realWorldApplications.map((app, index) => (
                    <li key={index}>{app}</li>
                  ))}
                </ul>
              </SectionCard>
              
              <SectionCard title="Risks & Guardrails" icon={<RisksIcon />}>
                <p>{summary.risksAndGuardrails}</p>
              </SectionCard>
        
              <SectionCard title="Glossary" icon={<GlossaryIcon />}>
                <dl className="space-y-3">
                  {summary.glossary.map((item, index) => (
                    <div key={index}>
                      <dt className="font-semibold text-slate-900">{item.term}</dt>
                      <dd className="pl-4 italic">{item.definition}</dd>
                    </div>
                  ))}
                </dl>
              </SectionCard>
              
              <SectionCard title="Questions to Ask" icon={<QuestionsIcon />}>
                <ul className="list-decimal list-inside space-y-2">
                  {summary.questionsToAsk.map((q, index) => (
                    <li key={index}>{q}</li>
                  ))}
                </ul>
              </SectionCard>
        
              <SectionCard title="Citations & Pull-quotes" icon={<QuotesIcon />}>
                <ul className="space-y-4">
                  {summary.citationsAndPullQuotes.map((c, index) => (
                    <li key={index}>
                      <blockquote className="border-l-4 border-slate-800 pl-4 italic">"{c.quote}"</blockquote>
                      <p className="text-right text-sm text-slate-600 mt-1">- {linkify(c.citation)}</p>
                    </li>
                  ))}
                </ul>
              </SectionCard>
          </div>

          <div className="mt-8">
            <Feedback />
          </div>
        </FadeIn>
    </div>
  );
};

export default ResultsDisplay;